#############################################################################
# Makefile for building: pyramidscoin-qt
# Generated by qmake (2.01a) (Qt 4.8.6) on: Pt 24. pa? 12:15:11 2014
# Project:  pyramidscoin-qt.pro
# Template: app
# Command: c:\QT\4.8.6\bin\qmake.exe USE_UPNP=- -o Makefile pyramidscoin-qt.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\QT\4.8.6\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: pyramidscoin-qt.pro  ../../../../qt/4.8.6/mkspecs/default/qmake.conf ../../../../qt/4.8.6/mkspecs/features/device_config.prf \
		../../../../qt/4.8.6/mkspecs/qconfig.pri \
		../../../../qt/4.8.6/mkspecs/features/qt_functions.prf \
		../../../../qt/4.8.6/mkspecs/features/qt_config.prf \
		../../../../qt/4.8.6/mkspecs/win32-g++/qmake.conf \
		../../../../qt/4.8.6/mkspecs/win32-g++-4.6/qmake.conf \
		../../../../qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		../../../../qt/4.8.6/mkspecs/features/default_pre.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/default_pre.prf \
		../../../../qt/4.8.6/mkspecs/features/release.prf \
		../../../../qt/4.8.6/mkspecs/features/debug_and_release.prf \
		../../../../qt/4.8.6/mkspecs/features/default_post.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/default_post.prf \
		../../../../qt/4.8.6/mkspecs/features/static.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/thread.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/rtti.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/exceptions.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/stl.prf \
		../../../../qt/4.8.6/mkspecs/features/warn_on.prf \
		../../../../qt/4.8.6/mkspecs/features/qt.prf \
		../../../../qt/4.8.6/mkspecs/features/moc.prf \
		../../../../qt/4.8.6/mkspecs/features/win32/windows.prf \
		../../../../qt/4.8.6/mkspecs/features/resources.prf \
		../../../../qt/4.8.6/mkspecs/features/uic.prf \
		../../../../qt/4.8.6/mkspecs/features/yacc.prf \
		../../../../qt/4.8.6/mkspecs/features/lex.prf \
		c:/qt/4.8.6/lib/qtmain.prl \
		c:/qt/4.8.6/lib/QtGui.prl \
		c:/qt/4.8.6/lib/QtNetwork.prl \
		c:/qt/4.8.6/lib/QtCore.prl
	$(QMAKE) USE_UPNP=- -o Makefile pyramidscoin-qt.pro
..\..\..\..\qt\4.8.6\mkspecs\features\device_config.prf:
..\..\..\..\qt\4.8.6\mkspecs\qconfig.pri:
..\..\..\..\qt\4.8.6\mkspecs\features\qt_functions.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\qt_config.prf:
..\..\..\..\qt\4.8.6\mkspecs\win32-g++\qmake.conf:
..\..\..\..\qt\4.8.6\mkspecs\win32-g++-4.6\qmake.conf:
..\..\..\..\qt\4.8.6\mkspecs\features\exclusive_builds.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\default_pre.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\default_pre.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\release.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\debug_and_release.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\default_post.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\default_post.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\static.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\thread.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\rtti.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\exceptions.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\stl.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\warn_on.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\qt.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\moc.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\win32\windows.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\resources.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\uic.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\yacc.prf:
..\..\..\..\qt\4.8.6\mkspecs\features\lex.prf:
c:\qt\4.8.6\lib\qtmain.prl:
c:\qt\4.8.6\lib\QtGui.prl:
c:\qt\4.8.6\lib\QtNetwork.prl:
c:\qt\4.8.6\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) USE_UPNP=- -o Makefile pyramidscoin-qt.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) C:/a/!pyra - etapy/2/pyramidscoin-block-source2/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/a/!pyra - etapy/2/pyramidscoin-block-source2/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) $(MAKE)
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

C:/a/!pyra - etapy/2/pyramidscoin-block-source2/src/leveldb/libleveldb.a: FORCE

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
